networks:
  default:
    driver: bridge

services:
  etcd:
    image: bitnami/etcd:3.5.17-debian-12-r0
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "https://etcd:2379,https://localhost:2379"
      ETCD_LISTEN_CLIENT_URLS: "https://0.0.0.0:2379"
      ETCD_CERT_FILE: "/certs/cert.pem"
      ETCD_KEY_FILE: "/certs/key.pem"
      ETCD_TRUSTED_CA_FILE: "/certs/ca.pem"
      ETCD_CLIENT_CERT_AUTH: "true"

      # Set etcdctl certs variables for simple debugging using dc exec
      ETCDCTL_CERT: "/certs/cert.pem"
      ETCDCTL_KEY: "/certs/key.pem"
      ETCDCTL_CACERT: "/certs/ca.pem"
    volumes:
      - "./test-certs:/certs"
    tmpfs:
      - /bitnami/etcd/data/
    ports:
      - "2379:2379"
